version: '3.8'
services:
  backend:
    image: wodnd0131/final_lv3:dev
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./data/springboot/logs:/var/logs
    environment:
      SPRING_ACTIVE_PROFILE: dev
    networks:
      - app-tier

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: final3_db
      MYSQL_USER: wodnd
      MYSQL_PASSWORD: wodnd
      SPRING_ACTIVE_PROFILE: dev
    ports:
      - '3307:3306'
    restart: always
    volumes:
      - 'mysqldb-data:/var/lib/mysql'
    networks:
      - app-tier

volumes:
  mysqldb-data:
    driver: local

networks:
  app-tier:
    driver: bridge
