version: '3.8'
services:
  backend:
    build:
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./data/springboot/logs:/var/logs
    environment:
      SPRING_ACTIVE_PROFILE: dev
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - app-tier

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: final3_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SPRING_ACTIVE_PROFILE: dev
    ports:
      - '3307:3306'
    restart: always
    volumes:
      - 'mysqldb-data:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-tier

volumes:
  mysqldb-data:
    driver: local

networks:
  app-tier:
    driver: bridge
